### ISSUE TITLE
omp_lib.h error when building 24.1 with ifx 2025.3.2

### ISSUE THREAD

**Issue by rsdmse** [gsabo/WIEN2k-Patches#4]
I am building WIEN2k 24.1 using Intel oneAPI ifx 2025.3.2 on Rocky 8.10. While most programs were built successfully, I got the following errors for lapw1:
```
/apps/software/standard/core/intel-compilers/2025.3.2/compiler/2025.3/opt/compiler/include/omp_lib.h(43): error #7747: Invalid parameter expression.   [4]
      parameter(omp_control_tool_result_kind=omp_integer_kind)
---------------------------------------------^
/apps/software/standard/core/intel-compilers/2025.3.2/compiler/2025.3/opt/compiler/include/omp_lib.h(44): error #6401: The attributes of this name conflict with those made accessible by a USE statement.   [OMP_ALLOCATOR_HANDLE_KIND]
      integer omp_allocator_handle_kind
```
The compiler flags are the same as the default, except I added `-march=skylake-avx512 -I/apps/software/standard/core/intel-compilers/2025.3.2/compiler/2025.3/opt/compiler/include`. Without the latter it would complain that `omp_lib.h` is not found. I also tried adding `-std=legacy` to no avail.

I have applied all the patches in this repo and read through your documentation at https://github.com/gsabo/WIEN2k-Docs/blob/main/WIEN2k24.1_Ubuntu22.04_Install_with_OneAPI(ifx).pdf. Thank you in advance for any suggestions.

**Comment by rsdmse** [comment]
Thank you for the advice! This time it worked with ifx 2025.3.2 by removing `-march=skylake-avx512` from the compiler flags. The additional include was still necessary for me.
